platform :ios, '13.0'

target 'SmartTour' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'iOSDropDown'
  pod 'TransitionButton'
  pod 'Alamofire', '~> 5.0.0-rc.1'
end
